#!/bin/sh
set -e

# GeekSlides CLI Docker entrypoint
#
# No arguments, stdout is a TTY   → show help message
# No arguments, stdout is piped   → print wrapper script (for > file or $(...))
# With arguments                   → execute the CLI command

if [ $# -eq 0 ]; then
  IMAGE="${GEEKSLIDES_IMAGE:-ciberado/geekslides-cli:latest}"
  PORT="${GEEKSLIDES_PORT:-3000}"

  if [ -t 1 ]; then
    # stdout is a terminal — show help
    cat <<HELP
GeekSlides CLI (Docker)

Install the wrapper script:

  docker run --rm ${IMAGE} > geekslides && chmod +x geekslides

Or using command substitution:

  cat <(docker run --rm ${IMAGE}) > geekslides && chmod +x geekslides

Then use it:

  ./geekslides dev                          Start dev server (port ${PORT})
  ./geekslides build --config config.json   Build production bundle
  ./geekslides pdf --config config.json     Export to PDF (requires :chromium tag)
  ./geekslides create --title "My Talk"     Scaffold a new deck

Environment variables (for the wrapper script):

  GEEKSLIDES_DIR    Deck directory to mount (default: current directory)
  GEEKSLIDES_PORT   Dev server port (default: ${PORT})

Image variants:

  ${IMAGE}          Slim image — all commands except PDF export
  ciberado/geekslides-cli:chromium   Includes Chromium for PDF export
HELP
  else
    # stdout is piped/redirected — emit the wrapper script
    cat <<WRAPPER
#!/bin/sh
set -e

# GeekSlides CLI wrapper
# Generated by: docker run --rm ${IMAGE}
#
# Usage:
#   ./geekslides dev                          Start dev server (port ${PORT})
#   ./geekslides build --config config.json   Build production bundle
#   ./geekslides pdf --config config.json     Export to PDF (requires :chromium tag)
#   ./geekslides create --title "My Talk"     Scaffold a new deck
#
# Environment variables:
#   GEEKSLIDES_DIR    Deck directory (default: current directory)
#   GEEKSLIDES_PORT   Dev server port (default: ${PORT})

IMAGE="${IMAGE}"
DECK_DIR="\${GEEKSLIDES_DIR:-\$PWD}"
PORT="\${GEEKSLIDES_PORT:-${PORT}}"

DOCKER_ARGS="--rm"

# Add -it if stdin is a terminal
if [ -t 0 ]; then
  DOCKER_ARGS="\${DOCKER_ARGS} -it"
fi

# Always mount the deck directory
DOCKER_ARGS="\${DOCKER_ARGS} -v \${DECK_DIR}:/deck"

# Command-specific handling
case "\${1:-}" in
  dev)
    DOCKER_ARGS="\${DOCKER_ARGS} -p \${PORT}:\${PORT}"
    shift
    exec docker run \${DOCKER_ARGS} "\${IMAGE}" dev --port "\${PORT}" --host 0.0.0.0 "\$@"
    ;;
  --version|-V)
    exec docker run \${DOCKER_ARGS} "\${IMAGE}" --version
    ;;
  *)
    exec docker run \${DOCKER_ARGS} "\${IMAGE}" "\$@"
    ;;
esac
WRAPPER
  fi

else
  exec node /app/packages/cli/dist/index.cjs "$@"
fi
